name: I Made This (showcase your work)
description: Share what you did with Powertools ❤️, e.g., blog post, workshops, presentation, sample apps, etc.
title: "[I Made This]: <TITLE>"
labels: ["customer_reference"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping spread the word out on Powertools, truly!
  - type: input
    id: content
    attributes:
      label: Link to your material
      description: |
        Please share the original link to your material.

        *Note: Short links will be expanded when added to Powertools documentation*
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe in one paragraph what's in it for them (readers)
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Preferred contact
      description: What's the preferred contact we should link next to this material?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: I understand this content may be removed from Powertools documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)
          required: true
  - type: textarea
    id: notes
    attributes:
      label: (Optional) Additional notes
      description: |
        Any notes you might want to share with us related to this material

        *Note: These notes are explicitly to Powertools maintainers. It will not be added to the community resources page.*
    validations:
      required: false
